INSERT INTO linechartdb.pontos (x, y, id_linechart) 
	VALUES (0.0, 5.0, 1)
INSERT INTO linechartdb.pontos (x, y, id_linechart) 
	VALUES (2.0, 0.0, 1)
INSERT INTO linechartdb.pontos (x, y, id_linechart) 
	VALUES (4.0, 7.0, 1)
INSERT INTO linechartdb.pontos (x, y, id_linechart) 
	VALUES (9.0, 2.0, 1)
INSERT INTO linechartdb.pontos (x, y, id_linechart) 
	VALUES (12.0, 10.0, 1)
